FROM ubuntu:16.04

RUN apt-get update -y
RUN apt-get install openjdk-8-jre -y
RUN apt-get install openjdk-8-jdk -y
RUN apt-get install maven -y

COPY . ./app

WORKDIR /app

RUN mvn clean
RUN mvn package

ENTRYPOINT [ "java","-jar","target/Docker-Demo-0.0.1-SNAPSHOT.jar" ]